BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Audit] ADD [client_group_id] UNIQUEIDENTIFIER;

-- AddForeignKey
ALTER TABLE [dbo].[Audit] ADD CONSTRAINT [FK_Audit_ClientGroup] FOREIGN KEY ([client_group_id]) REFERENCES [dbo].[ClientGroup]([id]) ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
