BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Availability] ADD [end_date] DATETIME2 NOT NULL CONSTRAINT [DF_Availability_EndDate] DEFAULT CURRENT_TIMESTAMP,
[start_date] DATETIME2 NOT NULL CONSTRAINT [DF_Availability_StartDate] DEFAULT CURRENT_TIMESTAMP;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
